---
apiVersion: v1
kind: Service
metadata:
  name: gctoutin-flask-service-test
  labels:
    app: gctoutin-flask-service-test
    username: gctoutin
    env: test
spec:
  type: ClusterIP
  selector:
    app: gctoutin-test-flask
  ports:
  - name: gctoutin-test-flask
    port: 5000
    targetPort: 5000
