---
apiVersion: v1
kind: Service
metadata:
  name: gctoutin-service-test
  labels:
    app: gctoutin-service-test
    username: gctoutin
    env: test
spec:
  type: ClusterIP
  selector:
    app: gctoutin-test-redis
  ports:
  - name: gctoutin-test-redis
    port: 6379
    targetPort: 6379
