---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gctoutin-hw7-worker-deployment
  labels:
    app: hw7-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw7-worker
  template:
    metadata:
      labels:
        app: hw7-worker
    spec:
      containers:
        - name: gctoutin-hw7-worker-deployment
          imagePullPolicy: Always
          image: gctoutin/hw7-wrk:latest
          command: ['python','worker.py']
          env:
          - name: "REDIS_IP"
            value: "10.109.68.104"  # CHANGED!
          #ports:
          #- name: http
          #  containerPort: 5000
