---
apiVersion: v1
kind: Service
metadata:
  name: gctoutin-service-hw7
  labels:
    app: gctoutin-service-hw7
    username: gctoutin
    env: test
spec:
  type: ClusterIP
  selector:
    app: gctoutin-hw7-redis
  ports:
  - name: gctoutin-hw7-redis
    port: 6379
    targetPort: 6379
