---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw5-hello-deployment
  labels:
    greeting: personalized
spec:
  replicas: 3
  selector:
    matchLabels:
      greeting: personalized
  template:
    metadata:
      labels:
        greeting: personalized
    spec:
      containers:
        - name: hellos
          image: ubuntu:18.04
          imagePullPolicy: Always
          env: 
            - name: "NAME"
              value: "Gabrielle"
            - name: POD_IP
              valueFrom: 
                fieldRef:
                  fieldPath: status.podIP
          command: ['sh', '-c', 'echo "Hello, $NAME from IP $POD_IP" && sleep 3600']
